apiversion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
      - name: {{ .Release.Name }}-my-api
        image: {{ .Values.image.backend }}
        resources:
          requests:
            memory: {{ .Values.resources.request.memory }}
            cpu: {{ .Values.resources.request.cpu }}
          limits:
            memory: {{ .Values.resources.limit.memory }}
            cpu: {{ .Values.resources.limit.cpu }}
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.env.secretName }}
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.env.secretName }}
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.env.secretName }}
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.env.secretName }}
              key: POSTGRES_DB
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.env.secretName }}
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.env.secretName }}
              key: AWS_SECRET_ACCESS_KEY
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.service.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.backend.name }}
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
  - protocol: TCP
    port: {{ .Values.service.backend.port }}
    targetPort: {{ .Values.service.backend.port }}
    nodePort: {{ .Values.nodePort.backend }}
  type: {{ .Values.service.backend.type }}
