apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-db
  labels:
    app: {{ .Release.Name }}-postgres-db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres-db
    spec:
      containers:
      - name: {{ .Release.Name }}-postgres-db
        image: {{ .Values.image.db }}
        resources:
          requests:
            memory: {{ .Values.resources.request.memory }}
            cpu: {{ .Values.resources.request.cpu }}
          limits:
            memory: {{ .Values.resources.limit.memory }}
            cpu: {{ .Values.resources.limit.cpu }}
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.env.secretName }}
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.env.secretName }}
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.env.secretName }}
              key: POSTGRES_DB
        ports:
        - containerPort: {{ .Values.service.db.port }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: {{ .Values.persistence.pvName }}
      volumes:
      - name: {{ .Values.persistence.pvName }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.pvcName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.db.name }}
spec:
  selector:
    app: {{ .Release.Name }}-postgres-db
  ports:
  - protocol: TCP
    port: {{ .Values.service.db.port }}
    targetPort: {{ .Values.service.db.port }}
