---
- name: Start the Hello World Application
  hosts: 178.128.83.86
  become: yes

  tasks:
    - name: Start the Hello World Application
      ansible.builtin.systemd:
        name: hi.service
        state: started
        enabled: yes 
