---
- name: Start the Hello World Application
  hosts: your_host_name_or_IP
  become: yes

  tasks:
    - name: Start the Hello World Application
      ansible.builtin.systemd:
        name: hi.service
        state: started
        enabled: yes 
