---
- name: Start Go Hello World Application
  hosts: all
  become: yes
  tasks:
    - name: Start the Hello-World service
      ansible.builtin.systemd:
        name: Hi.service
        state: started
        enabled: yes
