---
- name: Configure EC2 instance
  hosts: [ec2]
  become: yes
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
        state: present

    - name: Install Docker CE
      apt:
        pkg: docker-ce
        update_cache: yes
        state: present


      
      
