---
- name: Install Docker on Ubuntu
  hosts: aws_ec2 [ec2]  # It's referring to the plugin, not to a particular host.
  become: yes
  gather_facts: yes

  tasks:
  - name: Update apt-get
    apt: 
      update_cache: yes
      cache_valid_time: 3600

  - name: Install required system packages
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
      state: present

  - name: Add Docker's official GPG key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Verify if Docker's repository is added
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt-get
    apt: 
      update_cache: yes

  - name: Install Docker
    apt: 
      name: docker-ce
      state: present

      
      
