replicaCount: 1

image:
  backend: deatend/my-api:table
  frontend: deatend/my-api:pwd
  db: postgres:latest

service:
  backend:
    name: api-service
    type: NodePort
    port: 80
  frontend: 
    name: web-service
    type: NodePort
    port: 80
  db: 
    name: postgres-db-service
    type: NodePort
    port: 5432

env:
  secretName: my-secrets
   
resources:
  request:
    cpu: 0.5
    memory: 512Mi
  limit:
    cpu: 1
    memory: 1Gi

persistence:
  enabled: true
  pvName: db-pv-volume
  pvcName: db-pv-claim
  type: local
  storageClass: manual
  accessMode: ReadWriteMany 
  size: 10Gi
  hostPath: /Users/liolga/my-app/task/task25

nodePort:
  backend: 30000
  frontend: 30080 
