name: Deploy to Digital Ocean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
    
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
    
     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWD }}
     
     - name: Build and push
       uses: docker/build-push-action@v4
       with:
          push: true
          tags: deatend/ansible:img
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Connect to droplet
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.DROPLET_PORT }}
        script: |
          cd /home/ans
          docker run -it -e SSH_PRIVATE_KEY="$(cat ~/.ssh/id_rsa)" -e ANSIBLE_HOST_KEY_CHECKING=False -v /ansible/inventory.ini -v /root/.ssh/id_rsa -p 8080:8080 deatend/ansible:img

