name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install and configure Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
        echo "---" > inventory.ini
        echo " ansible_host=${{ secrets.REMOTE_HOST }} ansible_user=${{ secrets.REMOTE_USER }} " >> inventory.ini

    - name: Run Ansible playbook
      run: |
        ansible-galaxy collection install community.general
        ansible-playbook -i inventory.ini task8.yml
