name: Deploy Docker container to Digital Ocean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log into Digital Ocean
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_KEY }}

    - name: Install SSH client
      run: sudo apt-get install -y ssh

    - name: Copy SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy Docker container
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_HOST }} 'docker pull ${{ secrets.DOCKER_IMAGE }} && docker stop my-container || true && docker rm my-container || true && docker run -d --name my-container -p 80:80 my-docker-image'


