name: Trigger Ansible playbook on control node

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Trigger Ansible playbook on control node
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ansible_user@ansible_host 'ansible-playbook /home/lee/Desktop/ansible/ansible-ubuntu/task10.yml'
