name: Deploy Ansible and Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
     
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Ansible playbook and Docker run to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOUT_HOST }}
          username: ${{ secrets.REMOUT_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ansible-playbook -i inventory.ini task8.yml

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.REMOTE_IMAGE }}
