name: Docker Publish and Deploy
on:
push:
branches:
- main
jobs:
build-and-publish:
name: Build and Publish runs-on: buntu-latest
steps:
-name: Checkout uses: actions/checkout@v2
- name: Login to Docker Hub uses: docker/login-action@v1 with:
username: ${ secrets. DOCKER_USERNAME }} password: ${{ secrets.DOCKER_PASSWD }}
- name: Build and Push Docker image uses: docker/build-push-action@v2 with:
context:
push: true
tags: ${f secrets. DOCKER_IMAGE_TAG }}
