name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd ./task19
        terraform init

    - name: Terraform Apply
      run: |
        cd ./task19
        terraform apply -auto-approve

    - name: Configure instance with Ansible
      run: |
        # install ansible and dependencies
        sudo apt-get update
        sudo apt-get install -y ansible python3-pip
        sudo pip3 install boto boto3

        # run ansible playbook
        ansible-playbook -i ./task19/aws_ec2.yaml ./task19/playbook.yaml

     
