name: Deploye helm Chart fuk

on:
  push:
    branches: 
    - master 

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Start Minikube 
      run: |
        minikube start --driver=docker

    - name: Create Secret
      run: |
        kubectl create secret generic my-secrets 
        --from-literal=POSTGRES_USER=${{ secrets.POSTGRES_USER }} 
        --from-literal=POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} 
        --from-literal=POSTGRES_DB=${{ secrets.POSTGRES_DB }} 
        --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} 
        --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
      shell: powershell

    - name: Deploy Helm Chart
      run: |
        helm install task25 ./task25_helm/task25
