name: Run Ansible Playbook with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_ansible_playbook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Ansible playbook on remote VM
      env:
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      run: |
        export ANSIBLE_HOST_KEY_CHECKING=False
        ansible-playbook --inventory="$REMOTE_HOST," --user="$REMOTE_USER" --ask-pass --extra-vars "ansible_password=$REMOTE_PASSWORD" task8.yml
