on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install and configure Ansible
      run: |
          pip install ansible
          echo "---" > inventory.ini
          echo " ansible_host=${{ secrets.REMOTE_HOST }} ansible_user=${{ secrets.REMOTE_USER }} " >> inventory.ini

    - name: Deploy to Digital Ocean
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ansible-playbook -i inventory.ini task10.yml --private-key=private_key.pem
      env:
        DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
