name: Ansible Playbook Workflow

on:
  push:
    branches:
      - master

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute Ansible Playbook and run Docker image on remote VM
      uses: h/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Run the Ansible playbook on the remote VM
          ansible-playbook /home/lee/Desktop/ansible/ansible-ubuntu/task8.yml

          
