name: Ansible Playbook Workflow

on:
  push: # or any other event that triggers the workflow

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute Ansible Playbook and run Docker image on remote VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Run the Ansible playbook on the remote VM
          ansible-playbook /path/to/task10.yml

          
