name: Run Ansible Playbook on Remote Machine

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute Ansible playbook on remote machine
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST_SECRET }}
      run: |
        # Install the SSH key
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key

        # Add the remote host's key to the known_hosts file
        mkdir -p ~/.ssh
        ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts

        # Connect to the remote machine and run the Ansible playbook
        ssh -i private_key $REMOTE_HOST ansible-playbook /home/lee/Desktop/ansible/ansible-ubuntu/task10.yml


