name: CI/CD Pipeline

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Run Ansible playbook on VM
      env:
        VM_IP: ${{ secrets.REMOTE_HOST }}
        USER: ${{ secrets.REMOTE_USER }}
      run: |
        echo "Running Ansible playbook on VM"
        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r /path/to/playbook/task8.yml $USER@$VM_IP:/tmp
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USER@$VM_IP "ansible-playbook /tmp/task8.yml"
