name: Ansible Playbook Workflow

on:
  push:
    branches:
      - master

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute Ansible Playbook on remote VM
      run: |
        # Install SSH client on the GitHub Actions runner
        sudo apt-get update
        sudo apt-get install -y openssh-client

        # Save the private SSH key to a temporary file
        echo "${{ secrets.PRIVATE_KEY }}" > private_key
        chmod 600 private_key

        # Run the Ansible playbook on the remote VM (assuming it's already there)
        ssh -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "ansible-playbook /home/lee/Desktop/ansible/ansible-ubuntu/task8.yml"

        # Cleanup
        rm -f private_key
