name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start Minikube 
        run: |
          minikube start --driver=docker

      - name: Create Secret
        run: |
          kubectl create secret generic my-secrets \
          --from-literal=POSTGRES_USER=$(echo -n "${{ secrets.POSTGRES_USER }}") \
          --from-literal=POSTGRES_PASSWORD=$(echo -n "${{ secrets.POSTGRES_PASSWORD }}") \
          --from-literal=POSTGRES_DB=$(echo -n "${{ secrets.POSTGRES_DB }}" | base64) \
          --from-literal=AWS_ACCESS_KEY_ID=$(echo -n "${{ secrets.AWS_ACCESS_KEY_ID }}") \
          --from-literal=AWS_SECRET_ACCESS_KEY=$(echo -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}")
     
      - name: Deploy Helm Chart
        run: |
          helm install task25 ./task25_helm/task25
