name: Deploy to Digital Ocean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: deatend/ansible:img
