name: Deploy to Digital Ocean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
          context: OlgaLeeA/Projects
          dockerfile: OlgaLeeA/Projects/Docker
          push: true
          tags: deatend/ansible:img
          
    - name: Connect to droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.DROPLET_PORT }}
        script: |
          cd /home/ans
          docker run -d -p 8080:8080 deatend/ansible:img 
